
title: Corey Grone - Product Manager
url: 'http://coreygrone.com'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6




#Profile information
name: Corey Grone
tagline: Cloud Services Product Manager
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: corey@coreygrone.com
phone: 412 352 5140
website: coreygrone.com #do not add http://
linkedin: gronec
github: tr0n2ooo
twitter: '@coreygrone'

